@if ($activeTheme == 'fastfood')
    @includeIf('user-front.fastfood.partials.footer')
@elseif($activeTheme == 'bakery')
    @includeIf('user-front.bakery.partials.footer')
@elseif($activeTheme == 'pizza')
    @includeIf('user-front.pizza.partials.footer')
@elseif($activeTheme == 'coffee')
    @includeIf('user-front.coffee.partials.footer')
@elseif($activeTheme == 'medicine')
    @includeIf('user-front.medicine.partials.footer')
@elseif($activeTheme == 'grocery')
    @includeIf('user-front.grocery.partials.footer')
@elseif($activeTheme == 'beverage')
    @includeIf('user-front.beverage.partials.footer')
@elseif($activeTheme == 'seabbq')
    @includeIf('user-front.seabbq-desifoodie-desices.seabbq.partials.footer')
@elseif($activeTheme == 'desifoodie')
    @includeIf('user-front.seabbq-desifoodie-desices.desifoodie.partials.footer')
@elseif($activeTheme == 'desices')
    @includeIf('user-front.seabbq-desifoodie-desices.desices.partials.footer')
@endif
